### PR TITLE
Update main.php

### PR DESCRIPTION
**Pull request by samuelctn**
I've done your plugin m8 :D

### CODE REVIEW

**Comment by vickymaulana** [comment]
thanks for help me

**Comment by samuelctn** [comment]
XD

**Comment by vickymaulana** [comment]
I'm have Telegram Or Fb

Telegram : @vickym1010
Facebook : vicky maulana

Pada tanggal 8 Jun 2017 11.18, "Samy" <notifications@github.com> menulis:

**Comment by samuelctn** [comment]
They are too many vicky maulana on facebook, add me
https://www.facebook.com/omulunicorn21

**Comment by vickym1010** [comment]
I've invite you

Pada tanggal 8 Jun 2017 20.46, "Samy" <notifications@github.com> menulis:

**Pull request merged**
